### ISSUE TITLE
Is this still current?

### ISSUE THREAD

**Issue by dotnetprofessional** [Team997Coders/TestableRobot#1]
Looking at adding testing to our teams project for 2020 season. I followed the PR thread https://github.com/wpilibsuite/allwpilib/pull/1461 and see this project was last updated with the 202 alpha2019.0.0-alpha-3 and we're currently at 2019.4.1.

I'd like to leverage as much of your work as possible so would be good to know how ready this is for the 2020 season.

Btw great to see someone trying to demonstrate more software engineering rigor.

**Comment by dotnetprofessional** [comment]
I see there's been a rewrite for the 2020 season.

**Comment by chuckb** [comment]
This is Chuck Benedict. This is a project and work that I introduced to the team last year. Several folks on the team took up some of these techniques using JUnit and Mockito. I introduced both unit testing and integration testing concepts and the automation one can do with gradle. Also, I showed more advanced concepts using a dependency injection framework called Guice. It was probably more advanced than necessary.

Note that FIRST/WPI had not really embraced testability, to the point of actually making it difficult to do. I opened several issues in Github and I think they may have addressed. I also created some youtube content on the chsrobotics channel.

So it may well be that the work done in past projects has been incorporated and now easy to do with current versions of wpilib/vscode plugin.

Given my availability, I doubt I will be able to carry this work forward this year, but would be willing to work with you to hand it off/test it out with current code.

You can contact me at 832-571-0772 or this email.

Regards,
Chuck Benedict

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dotnetprofessional** [comment]
Thanks Chuck... I just realized they rewrote the command libraries which on the surface look more testable. Haven't had a chance to install the beta for 2020 yet. If you're still mentoring I'll keep you posted on our progress.

Thanks.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chuckb** [comment]
My approach is that I wanted the students to be able to run their code as soon as possible, because for me, it was supremely annoying to hear "I am done until I get the robot". In real-time systems, automated testing can only go so far, and some believe it is not even worth it (something I disagree with) and, further, some confuse simulation and testing. I did find that some students really lit up when they found out they could run pieces of their code without needing hardware. But you do have to know how to develop those commands and subsystems with testability in mind.

--Chuck

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
